name: CodeDay
author: MatthewStanciu
version: 1.0
main: net.extrillius.CodeDay.CodeDay

commands:
  checkpoint:
    description: Set checkpoint
  startloc:
    description: set the starting point
  join:
    description: joins a game